### ISSUE TITLE
`README.rst` on pypi.python.org does not render properly

### ISSUE THREAD

**Issue by vlcinsky** [ical2org-py/ical2org.py#27]
I have noticed, that `README.rst` does not render properly on pypi (this is happing quite often).

I got an idea how to fix it easily (probably adding one line into `setup.cfg`) and will hopefully do that within following days (for next release).

**Comment by spookylukey** [comment]
Thanks for letting us know, fixed now in 0.4 - https://pypi.org/project/ical2orgpy/0.4.0/
