### ISSUE TITLE
Handle events with RECURRENCE-ID

### ISSUE THREAD

**Issue by michitux** [ical2org-py/ical2org.py#33]
When you edit an event of series of recurring events, Thunderbird will leave the original event untouched but instead generate a separate, non-recurring (?) VEVENT with the same UID and a property `RECURRENCE-ID` that specifies which event in the series it replaces. From what I see in my calendar export, this event should then replace the original event. See also [here](https://icalevents.com/4437-correct-handling-of-uid-recurrence-id-sequence/) for a more detailed discussion. Currently, in the import, I get both the original event of the series and the changed event. To fix this, ical2org.py would probably need to group events by UID, look for a property "RECURRENCE-ID" and then remove these occurrences in the main event that specifies the recurring event. The link suggests this might be more complicated though. Nevertheless, even a simple handling could already be an improvement.

**Comment by asoroa** [comment]
Hi, sorry for taking so long answering.
Unfortunately, implementing this would require a two-pass approach, first collecting all the events, then filtering out according to the rules you explain above. It would be good to see (as well as other stuff, such as monthly recurring events), but currently I lack the time to implement it.
I'll leave the issue open though, as a gently reminder ;-)

**Comment by michitux** [comment]
No problem, I can fully understand this. If I should need this feature more urgently (so far I have used ical2org.py only for importing some old data), I might also consider implementing this myself. Thank you very much for providing this useful script!

**Comment by spookylukey** [comment]
This is fixed now, since d71d06e665e3bad24459de3e8fd5dac353910ebe thanks to implementation in [recurring-ical-events](https://github.com/niccokunzmann/python-recurring-ical-events).
