### ISSUE TITLE
Please add verbose option which would help diagnose refused elements

### ISSUE THREAD

**Issue by olberger** [ical2org-py/ical2org.py#43]
By default, the 90 days window can be confusing, as elements can be silently discarded because they're outside the 90 days frame.

It would be interesting to have a verbose option allowing to get messages (on stderr ?) about such discarded elements.

Other cases of useful verbose messages may of course apply.

Hope this sounds useful.

Thanks in advance.

**Comment by spookylukey** [comment]
I think this would be technically very difficult to do, especially as we now rely on [recurring-ical-events](https://github.com/niccokunzmann/python-recurring-ical-events) to do the heavy lifting, and it doesn't provide that feature.

Even in theory, this is hard, depending on your search strategy. When searching for a needle in a haystack, describing all the things you have rejected as not a needle may not be possible - for example, if you used a large magnet to pull the needle to you, you simply wouldn't have looked at most things.

So, I'm going to close this as impractical. sorry!
